#!/bin/bash
# Batch translate Chinese comments to English in Python files

echo "Translating remaining Chinese comments..."

# List of files to translate
FILES=(
  "src/redmine_mcp_server/dws/services/email_service.py"
  "src/redmine_mcp_server/dws/services/report_generation_service.py"
  "src/redmine_mcp_server/dws/services/report_service.py"
  "src/redmine_mcp_server/dws/services/quality_service.py"
  "src/redmine_mcp_server/dws/services/analysis_service.py"
  "src/redmine_mcp_server/dws/services/trend_analysis_service.py"
  "src/redmine_mcp_server/dws/services/sync_service.py"
  "src/redmine_mcp_server/dws/repository.py"
  "src/redmine_mcp_server/scheduler/ads_scheduler.py"
  "src/redmine_mcp_server/scheduler/daily_stats.py"
)

for file in "${FILES[@]}"; do
  if [ -f "$file" ]; then
    echo "Processing $file..."
    # Use sed to replace common Chinese terms
    sed -i 's/订阅报告/subscription report/g' "$file"
    sed -i 's/订阅/subscription/g' "$file"
    sed -i 's/报告/report/g' "$file"
    sed -i 's/推送/push/g' "$file"
    sed -i 's/邮件/email/g' "$file"
    sed -i 's/项目/project/g' "$file"
    sed -i 's/用户/user/g' "$file"
    sed -i 's/配置/configuration/g' "$file"
    sed -i 's/服务/service/g' "$file"
    sed -i 's/生成/generate/g' "$file"
    sed -i 's/发送/send/g' "$file"
    sed -i 's/接收/receive/g' "$file"
    sed -i 's/连接/connection/g' "$file"
    sed -i 's/数据库/database/g' "$file"
    sed -i 's/仓库/warehouse/g' "$file"
    sed -i 's/调度器/scheduler/g' "$file"
    sed -i 's/任务/job/g' "$file"
    sed -i 's/定时/scheduled/g' "$file"
    sed -i 's/执行/execute/g' "$file"
    sed -i 's/统计/statistics/g' "$file"
    sed -i 's/分析/analysis/g' "$file"
    sed -i 's/趋势/trend/g' "$file"
    sed -i 's/状态/status/g' "$file"
    sed -i 's/优先级/priority/g' "$file"
    sed -i 's/详细/detailed/g' "$file"
    sed -i 's/简要/brief/g' "$file"
    sed -i 's/完整/comprehensive/g' "$file"
    sed -i 's/高优先级/high priority/g' "$file"
    sed -i 's/人员负载/team workload/g' "$file"
    sed -i 's/质量报告/quality report/g' "$file"
    sed -i 's/保存/save/g' "$file"
    sed -i 's/创建/create/g' "$file"
    sed -i 's/验证/validate/g' "$file"
    sed -i 's/测试/test/g' "$file"
    sed -i 's/检查/check/g' "$file"
    sed -i 's/获取/get/g' "$file"
    sed -i 's/返回/return/g' "$file"
    sed -i 's/参数/parameter/g' "$file"
    sed -i 's/结果/result/g' "$file"
    sed -i 's/数据/data/g' "$file"
    sed -i 's/入口/entry/g' "$file"
    sed -i 's/统一/unified/g' "$file"
    sed -i 's/实例/instance/g' "$file"
    sed -i 's/类/class/g' "$file"
    sed -i 's/方法/method/g' "$file"
    sed -i 's/函数/function/g' "$file"
    sed -i 's/模块/module/g' "$file"
    sed -i 's/接口/interface/g' "$file"
    sed -i 's/实现/implementation/g' "$file"
    sed -i 's/逻辑/logic/g' "$file"
    sed -i 's/处理/process/g' "$file"
    sed -i 's/加载/load/g' "$file"
    sed -i 's/保存/save/g' "$file"
    sed -i 's/更新/update/g' "$file"
    sed -i 's/删除/delete/g' "$file"
    sed -i 's/查询/query/g' "$file"
    sed -i 's/插入/insert/g' "$file"
    sed -i 's/存在/exists/g' "$file"
    sed -i 's/初始化/initialize/g' "$file"
    sed -i 's/启动/start/g' "$file"
    sed -i 's/关闭/shutdown/g' "$file"
    sed -i 's/运行/running/g' "$file"
    sed -i 's/监听/listening/g' "$file"
    sed -i 's/端口/port/g' "$file"
    sed -i 's/端点/endpoint/g' "$file"
    sed -i 's/请求/request/g' "$file"
    sed -i 's/响应/response/g' "$file"
    sed -i 's/成功/success/g' "$file"
    sed -i 's/失败/failure/g' "$file"
    sed -i 's/错误/error/g' "$file"
    sed -i 's/异常/exception/g' "$file"
    sed -i 's/警告/warning/g' "$file"
    sed -i 's/信息/info/g' "$file"
    sed -i 's/调试/debug/g' "$file"
    sed -i 's/日志/log/g' "$file"
    sed -i 's/时间/time/g' "$file"
    sed -i 's/日期/date/g' "$file"
    sed -i 's/周期/period/g' "$file"
    sed -i 's/间隔/interval/g' "$file"
    sed -i 's/频率/frequency/g' "$file"
    sed -i 's/渠道/channel/g' "$file"
    sed -i 's/地址/address/g' "$file"
    sed -i 's/名称/name/g' "$file"
    sed -i 's/类型/type/g' "$file"
    sed -i 's/级别/level/g' "$file"
    sed -i 's/语言/language/g' "$file"
    sed -i 's/格式/format/g' "$file"
    sed -i 's/内容/content/g' "$file"
    sed -i 's/主题/subject/g' "$file"
    sed -i 's/正文/body/g' "$file"
    sed -i 's/模板/template/g' "$file"
    sed -i 's/HTML/html/g' "$file"
    sed -i 's/格式/format/g' "$file"
    sed -i 's/支持/support/g' "$file"
    sed -i 's/多语言/multi-language/g' "$file"
    sed -i 's/国际化/internationalization/g' "$file"
    sed -i 's/本地化/localization/g' "$file"
    sed -i 's/翻译/translation/g' "$file"
    sed -i 's/默认/default/g' "$file"
    sed -i 's/可选/optional/g' "$file"
    sed -i 's/必需/required/g' "$file"
    sed -i 's/列表/list/g' "$file"
    sed -i 's/字典/dictionary/g' "$file"
    sed -i 's/数组/array/g' "$file"
    sed -i 's/字符串/string/g' "$file"
    sed -i 's/整数/integer/g' "$file"
    sed -i 's/布尔/boolean/g' "$file"
    sed -i 's/对象/object/g' "$file"
    sed -i 's/属性/attribute/g' "$file"
    sed -i 's/值/value/g' "$file"
    sed -i 's/键/key/g' "$file"
  fi
done

echo "Translation complete!"
echo "Please review and manually fix any awkward translations."
